# -*- coding: utf-8 -*-
"""Anomaly detection #3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mfqs604BkYlb6VltCxxu2S3uQAQWdrUj
"""

!pip install ultralytics==8.0.20

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

from google.colab import drive
drive.mount('/content/drive')

ls

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Anomaly detection

!yolo task=detect mode=train model=yolov8s.pt data= data.yaml epochs=1 imgsz=640 plots=True

!yolo task=detect mode=val model=runs/detect/train/weights/best.pt data=data.yaml

!yolo task=detect mode=predict model=runs/detect/train/weights/best.pt conf=0.25 source=data/test/images save=True

!yolo task=detect mode=predict model=runs/detect/train/weights/best.pt source="/content/drive/MyDrive/Anomaly detection/data/crash26.mp4" save=True